name: data100-FA23

channels:
- conda-forge

dependencies:
- python==3.11.0
- git==2.39.1
- jupyter-resource-usage==1.0.0
- jupyterlab==4.0.10
- jupyterlab-favorites==3.2.1
- jupyterlab_server==2.25.2
- jupyterlab_widgets==3.0.9
- jupyter_server==2.12.4
- nbgitpuller==1.1.1
- notebook==7.0.6
- folium==0.15.1
- h5netcdf==1.3.0
- ipywidgets==8.0.7
- jupysql==0.10.7
- jupyter-archive==3.4.0
- matplotlib==3.8.2
- mdit-py-plugins==0.4.0
- numpy==1.26.3
- otter-grader==5.2.2
- pandas==2.1.4
- plotly==5.18.0
- requests==2.31.0
- scikit-image==0.22.0
- scikit-learn==1.3.2
- scipy==1.11.4
- seaborn==0.12.2
- statsmodels==0.14.1
- tensorflow==2.15.0
- tensorflow-cpu==2.15.0
- sqlalchemy==2.0.25
- mlxtend==0.23.0
- geopandas==0.14.2
- geopy==2.4.1
- lifelines==0.27.8
- pycountry==22.3.5
- pip
- pip:
  # - -r infra-requirements.txt
  - ipywidgets==8.0.7
  # disable until fixed (probably this:  https://github.com/jupyterlab/jupyter-collaboration/issues/162)
  # - jupyter_collaboration==1.0.1
  - jupyterhub==4.0.2
  - nbconvert==7.14.1
  - pytest-notebook==0.10.0
  - gh-scoped-creds==4.1
  - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
  - ydata-profiling==4.6.4
