name: data100
channels:
- defaults
- pytorch
dependencies:
- attrs=19.3.0
- beautifulsoup4=4.8.2
- bleach=3.1.0
- coverage=5.0.3
- decorator=4.4.1
- html5lib=1.0.1
- ipykernel=5.1.4
- ipython=7.9.0
- ipython_genutils=0.2.0
- ipywidgets=7.5.1
- jsonschema=3.2.0
- lxml=4.5.0
- matplotlib=3.1.2
- networkx=2.4
- nodejs=13.7.0
- numpy=1.18.1
- oauthlib=3.0.1
- pandas=0.25.3
- pandoc=2.9.1.1
- pandocfilters=1.4.2
- pip=20.0.2
- protobuf=3.11.2
- pygments=2.5.2
- pytest=5.3.5 # needed for jupyter-tree-download
- python=3.7.6
- python-dateutil=2.8.1
- pytz=2019.3
- pyzmq=18.1.1
- requests=2.22.0
- requests-oauthlib=1.2.0
- setuptools=45.1.0
- sqlalchemy=1.3.13
- sqlite=3.30.1
- statsmodels=0.11.0
- sympy=1.5.1
- tensorflow=2.0.0
- tornado=6.0.3
- traitlets=4.3.3
- widgetsnbextension=3.5.1
- xarray=0.14.1
- xz=5.2.4
- zeromq=4.3.2
- graphviz=2.42.3
- pytorch=1.4.0
- pip:
  - -r requirements.txt
